# gcloud container clusters get-credentials onxp-bootcamp-cluster --region=us-central1-a
# kubectl -n exercise apply -f pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: exercise-app
  labels:
    app: exercise-app
spec:
  containers:
    - name: exercise-app
      image: glendmaatita/exercise-app
      ports:
        - containerPort: 3000
    - name: sidecar-busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo Hello from the sidecar; sleep 3600; done']
