# kubectl -n elastic-system apply -f hostpath-pvc.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-elasticsearch-pv
  labels:
    type: hostpath-elasticsearch
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/elasticsearch
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-elasticsearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      type: hostpath-elasticsearch
