# kubectl -n observability apply -f bastion.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  labels:
    app: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion
          image: glendmaatita/bastion:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: grafana-volume
            mountPath: /var/lib/grafana
          - name: grafana-ini-volume
            mountPath: /etc/grafana
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-ini-volume
          persistentVolumeClaim:
            claimName: grafana-ini-pvc

---