# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm install postgresql -f values.yml bitnami/postgresql -n database

# docs: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
# connect to Replica
# - via Service: psql -U onxp -d example_db -h postgresql-onxp-postgresql-read-replica.exercise.svc.cluster.local
image:
  tag: 13.13.0

auth:
  enablePostgresUser: true
  postgresPassword: "onxpsecret"
  username: "onxp"
  password: "onxpsecret"
  database: "example_db"

architecture: replication

replication:
  synchronousCommit: "off"
  numSynchronousReplicas: 2
  applicationName: "onxp-postgresql"

primary:
  persistence:
    enabled: true

readReplicas:
  name: "onxp-postgresql-read-replica"
  replicaCount: 2
  persistence:
    enabled: true

volumePermissions:
  enabled: true

initdbScripts:
  init_db.sql: |
    CREATE DATABASE exercise_app;
    CREATE DATABASE sonarqube;