# kubectl -n observability apply -f volume.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uptime-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi