# kubectl -n atlantis apply -f pvc.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: atlantis-kubeconf-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: atlantis-dir-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi