# kubectl -n observability apply -f deployment.yaml
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: grafana-volume
            mountPath: /var/lib/grafana
          - name: datasource-volume
            mountPath: /etc/grafana/provisioning/datasources/datasource.yml
            subPath: datasource.yml
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: hostpath-grafana-pvc
        - name: datasource-volume
          configMap:
            name: datasource-config

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-config
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  ingressClassName: public
  rules:
    - host: grafana.ops.onxp.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: grafana
                port: 
                  number: 80
  tls:
    - hosts:
        - grafana.ops.onxp.net
      secretName: tls-ops-grafana
