# helm repo add glitchtip https://gitlab.com/api/v4/projects/16325141/packages/helm/stable
# helm install glitchtip glitchtip/glitchtip -f values.yaml -n observability

# register
# username: glend.maatita@gmail.com
# password: DdCBd55W1TL78onOFTwi
---
image:
  tag: v4.1.4
  pullPolicy: IfNotPresent

worker:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPU: 80
    targetMemory: 80
  livenessProbe: {}

web:
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: public # using nginx if not using microk8s
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - host: glitchtip.ops.onxp.net
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: tls-secret-glitchtip
        hosts:
          - glitchtip.ops.onxp.net

env:
  normal:
    GLITCHTIP_DOMAIN: https://glitchtip.ops.onxp.net
  secret:
    SECRET_KEY: BCmpQYr7kg2WGQMi4GcM
    DATABASE_URL: postgres://onxp:onxpsecret@postgresql-primary.database:5432/glitchtip
    REDIS_URL: redis://redis-master


postgresql:
  enabled: false

redis:
  enabled: false